version: "3"
services:
  nginx:
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      - ./public:/usr/share/nginx/html
#    ports:
#      - "80:80"
#      - "443:443"
    depends_on:
      - server

  client:
    image: node
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: node:alpine
    restart: always
    ports:
      - "4000:4000"
      - "7000:7000"
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: