import {Router} from "express";
import userController from "../controllers/user-controller.js";
import AffiliateController from "../controllers/affiliateController.js";
import RewardController from "../controllers/rewardController.js";
import gameController from "../controllers/gameController.js";
import supportController from "../controllers/supportController.js";
import marketController from "../controllers/marketController.js";
import botController from "../controllers/botController.js";
import historyController from "../controllers/historyController.js";
import depositController from "../controllers/depositController.js";
import adminController from "../controllers/adminController.js";
import withdrawController from "../controllers/withdrawController.js";
import linkedCodeController from "../controllers/linkedCodeController.js";
import botEntityController from "../controllers/botEntityController.js";
import authMiddleware from "../middlewares/auth-middleware.js";

const router = new Router();

router.post('/getUser', userController.getUser);
router.get('/getUserAvatar', userController.getUserAvatar);
router.post('/logout', userController.logout);
router.get('/refresh', userController.refresh);
router.post('/verifyDescription', userController.verifyDescription);
router.post('/createAffiliate', authMiddleware, AffiliateController.createAffiliate);
router.get('/getAffiliate', authMiddleware, AffiliateController.getAffiliate);
router.patch('/affiliateBalance', authMiddleware, AffiliateController.getBalance);
router.get('/code', AffiliateController.checkForCode);
router.patch('/code', AffiliateController.linkCode);
router.post('/code', AffiliateController.codeUse);
router.post('/unlinkCode', AffiliateController.unlinkCode);
router.post('/reward', RewardController.addReward);
router.post('/getReward', authMiddleware, RewardController.getReward);
router.put('/boost', userController.addExp);
router.put('/claim', authMiddleware, userController.claim);
router.patch('/tip', authMiddleware, userController.tip);
router.get('/leaders', userController.getLeaders);
router.post('/game', authMiddleware, gameController.createGame);
router.patch('/game', authMiddleware, gameController.joinGame);
router.get('/game', gameController.getGames);
router.post('/cancelGame', authMiddleware, gameController.cancelGame);
router.post('/endGame', gameController.deleteGame);
router.get('/history', authMiddleware, userController.getHistory);
router.post('/history', historyController.addHistory);
router.post('/support', authMiddleware, supportController.sendQuestion);
router.get('/support', supportController.getQuestions);
router.put('/support', supportController.answer);
router.get('/answers', authMiddleware, supportController.getAnswers);
router.post('/market', authMiddleware, marketController.addItemMarket);
router.get('/market', marketController.getItemsMarket);
router.put('/market', authMiddleware, marketController.buyItemMarket);
router.post('/marketRemove', authMiddleware, marketController.removeItemMarket);
router.post('/completeWithdraw', botController.completeWithdraw);
router.post('/bot', botController.addItemBot);
router.get('/getUserItems', authMiddleware, botController.getUserItems);
router.get('/withdraw', botController.getWithdrawData);
router.post('/paymentAddress', authMiddleware, depositController.createPaymentAddress);
router.post('/findAddress', authMiddleware, depositController.findAddress);
router.post('/changeRole', authMiddleware, adminController.changeRole);
router.post('/addBalance', authMiddleware, adminController.addBalance);
router.post('/reduceBalance', authMiddleware, adminController.reduceBalance);
router.post('/changeLevel', authMiddleware, adminController.changeLevel);
router.post('/withdraw', authMiddleware, withdrawController.addToQueue);
router.post('/increaseOnline', authMiddleware, adminController.increaseOnline);
router.post('/decreaseOnline', authMiddleware, adminController.decreaseOnline);
router.post('/banUser', authMiddleware, adminController.banUser);
router.post('/unbanUser', authMiddleware, adminController.unbanUser);
router.post('/notification-webhook', depositController.getNotified);
router.get('/payments', authMiddleware, userController.getPayments);
router.get('/adminUser', authMiddleware, adminController.getUser);
router.patch('/joinWithGems', authMiddleware, gameController.joinWithGems);
router.post('/createWithGems', authMiddleware, gameController.createWithGems);
router.get('/linkedCode', authMiddleware, linkedCodeController.getLinkedCode);
router.post('/linkedCode', authMiddleware, linkedCodeController.linkLinkedCode);
router.get('/botEntity', botEntityController.getBots);
router.post('/botEntity', botEntityController.addBot);
router.get('/giveawayItems', authMiddleware, botController.getGiveawayItems);
router.post('/startGiveaway', botController.startGiveaway);
router.get('/24hours', historyController.get24hours);
router.get('/getFake', authMiddleware, adminController.getFake);
router.post('/changeTaxPath', authMiddleware, adminController.changeTaxReceiver);
router.get('/receiver', authMiddleware, adminController.getReceiver);
router.get('/taxDataAdmin', authMiddleware, adminController.getTaxInfo);
router.post('/cancelTaxChange', authMiddleware, adminController.cancelTaxChange);
router.post('/checkIncluded', botController.checkIncluded);
router.post('/sendMessage', authMiddleware, userController.sendMessage);

export default router;